# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: /home/runner/work/winter23/winter23/measurements_frontend/measurements/package-lock.json
    - run: npm i
        working-directory: measurements_frontend/measurements
      - run: npm run build --if-present
        working-directory: measurements_frontend/measurements
      - name: zip build
        run: zip -r build/artifact.zip build
        working-directory: measurements_frontend/measurements
      - uses: actions/upload-artifact@v1
        with:
          name: react_build
          path: measurements_frontend/measurements/build
      - run: npm test
        working-directory: measurements_frontend/measurements
